[build]
  base = "/"
  publish = ".next"
  command = "npm run build"
  functions = "/netlify"

[build.environment]
  NEXT_SERVERLESS = "true"
  SANITY_PROJECT_ID="o13itn6x"
  SANITY_DATASET="production"
  BUILD_LANGUAGES = "en-US,it-IT"
  BUILD_CMS = "sanity"
  CL_CLIENT_ID = "Yah4XOhN3DcwZPKWSnCSDj6dpkhvbo4vaosnmfMET0I"
  CL_ENDPOINT = "https://dentsu-creative.commercelayer.io"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[plugins]]
  package = "netlify-plugin-inline-functions-env"
  [plugins.inputs]
    buildEvent = "onBuild"
